### ISSUE TITLE
Unresolved databinding references

### ISSUE THREAD

**Issue by tigrettin** [stripe-samples/sample-store-android#33]
Hello,

I've been trying to implement Stripe Android SDK to my app (already did on the iOS version, so have a working backend) without cloning the whole repository.

https://github.com/stripe-samples/sample-store-android/blob/master/app/src/main/java/com/stripe/samplestore/PaymentActivity.kt

Getting "unresolved reference" errors on line 33 and 34 here. As far as I understand, these two somehow bind the layout files cart_item.xml and payment_activity.xml to the activity.

Where do they come from and which file should I implement to get them to work?

Any suggestion or feedback will be welcomed and greatly appreciated.

Thank you!

**Comment by mshafrir-stripe** [comment]
@tigrettin what version of Gradle and Android Gradle Plugin are you currently using?

**Comment by mshafrir-stripe** [comment]
The app takes advantage of [Android View Binding](https://developer.android.com/topic/libraries/view-binding) [0]. You'll need to make sure you've enabled this in your app as well. I also recommend updating to the latest version of Android Gradle Plugin, 3.6.3, if you haven't already.

[0] https://developer.android.com/topic/libraries/view-binding

**Comment by tigrettin** [comment]
Hey there, thanks for the quick response!

Apologies, my bad. I hadn't included those two layout resource files in my project:

https://github.com/stripe-samples/sample-store-android/blob/master/app/src/main/res/layout/payment_activity.xml

https://github.com/stripe-samples/sample-store-android/blob/master/app/src/main/res/layout/cart_item.xml

All works now.
